application: onno-eberhard
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# Maintenance Page
# - url: /(.*)
#   static_files: maintenance.html
#   upload: maintenance.html

 - url: /
   script: main.app
   secure: always

 - url: /main
   static_dir: main


 # APIs

 - url: /_ah/api/.*
   script: endpoint.api


 # Kevin Bacon

 - url: /(kevinBacon|kevinbacon)
   script: kevinBacon.app
   secure: always

 - url: /kb
   static_dir: Kevin Bacon


 # ePotato

 - url: /(ePotato|epotato)
   static_files: ePotato/index.html
   upload: ePotato/index.html
   secure: always

 - url: /(ePotato|epotato)/(Privacy|privacy)
   static_files: ePotato/privacy.html
   upload: ePotato/privacy.html
   secure: always

 - url: /(ePotato|epotato)/ios-licenses
   static_files: ePotato/ios-licenses.html
   upload: ePotato/ios-licenses.html
   secure: always

 - url: /ePotato
   static_dir: ePotato


 # tau

 - url: /tau
   static_files: tau/index.html
   upload: tau/index.html
   secure: always

 - url: /tau/local
   static_files: tau/index.html
   upload: tau/index.html
   secure: never

 - url: /tau
   static_dir: tau


 # archive

 - url: /archive
   static_files: archive/index.html
   upload: archive/index.html
   secure: always

 - url: /archive
   static_dir: archive


 # SSL & General

 - url: /.well-known/acme-challenge/FjJmBoWxCfWeaOynL4yxKoldg0bv1eoJOED8GpYnG4c
   static_files: _certificates/letsencrypt_challenge1.txt
   upload: _certificates/letsencrypt_challenge1.txt

 - url: /.well-known/acme-challenge/h13rYINHPiAlzFwW2_6z3nJfBioga9QUDLtoC2tlxwQ
   static_files: _certificates/letsencrypt_challenge2.txt
   upload: _certificates/letsencrypt_challenge2.txt

 - url: /assets
   static_dir: assets

 - url: /sitemap.txt
   static_files: sitemap.txtx^
   upload: sitemap.txt

 - url: /(.*)
   static_files: 404.html
   upload: 404.html


libraries:

 - name: webapp2
   version: "2.5.2"

 - name: jinja2
   version: "2.6"
